main:
    path:     /
    defaults: { _controller: WorkBundle:Default:index }

find_work:
    path: /findwork
    defaults: { _controller: WorkBundle:Worker:findWork }

post_worker:
    path: /postworker
    defaults: { _controller: WorkBundle:Worker:postWorker }

post_work:
    path: /posthire
    defaults: { _controller: WorkBundle:Employer:postWork }

find_worker:
    path: /findhire
    defaults: { _controller: WorkBundle:Employer:findWorker }

add_worker:
    path: /addWorker
    defaults: { _controller: WorkBundle:Worker:addWorker }

add_work:
    path: /addWork
    defaults: { _controller: WorkBundle:Employer:addWork }

admin_issues:
    path: /admin/
    defaults: { _controller: WorkBundle:Admin:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_delete_issue:
    path: /admin/deleteIssue
    defaults: { _controller: WorkBundle:Admin:deleteIssue }

image_upload:
    path: /admin/imageUpload
    defaults: { _controller: WorkBundle:Image:imageUpload }

image_saving:
    path: /admin/imageSaving
    defaults: { _controller: WorkBundle:Image:imageSaving }
    defaults: { _controller: WorkBundle:Image:imageSaving }
